(function(){
'use strict';
var client=null,session=null;
function q(s,r){return(r||document).querySelector(s)}
function e(v){return String(v==null?'':v).replace(/[&<>"']/g,function(a){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[a]})}
function nice(v){return String(v||'').replace(/_/g,' ').replace(/\b\w/g,function(a){return a.toUpperCase()})}
function set(s,m,t){var x=typeof s==='string'?q(s):s;if(x){x.textContent=m||'';x.dataset.type=t||'info'}}
function toast(m,t){if(window.GEESPortalUI&&window.GEESPortalUI.toast)window.GEESPortalUI.toast(m,t||'success')}
async function boot(){client=window.GEESSupabase;if(window.GEESWaitForSupabaseClient)client=await window.GEESWaitForSupabaseClient();session=window.GEESCurrentPortalSession;if(window.GEESAuthService&&window.GEESAuthService.getPortalSession)session=await window.GEESAuthService.getPortalSession();if(!client)throw new Error('Supabase client unavailable.');if(!session||session.source!=='supabase')throw new Error('Real Supabase admin login required.');if(session.role!=='admin'&&session.role!=='super_admin')throw new Error('Admin access required.');}
async function rows(req){var r=await req;if(r.error)throw new Error(r.error.message);return r.data||[]}
function counts(list,role){return list.filter(function(x){return !role||x.role===role}).length}
function options(vals,current){return vals.map(function(v){return '<option value="'+e(v)+'" '+(v===current?'selected':'')+'>'+e(nice(v))+'</option>'}).join('')}
function detailsLink(id){return '/portal/admin/user-details.html?id='+encodeURIComponent(id)}
async function refresh(root){var users=await rows(client.from('profiles').select('id,email,full_name,phone,role,status,team_id,created_at,updated_at').order('created_at',{ascending:false}));q('[data-stat="users"]',root).textContent=users.length;q('[data-stat="students"]',root).textContent=counts(users,'student');q('[data-stat="agents"]',root).textContent=counts(users,'agent');q('[data-stat="staff"]',root).textContent=counts(users,'staff');var roleVals=['student','agent','staff','admin','super_admin'];var statusVals=['pending','active','rejected','suspended','archived'];var teamVals=['','staff','ekhlas','maanisha','rafshan','seo'];q('[data-table="users"]',root).innerHTML=users.length?users.map(function(u){var roleControl=session.role==='super_admin'?'<select data-role-control>'+options(roleVals,u.role)+'</select>':'<span class="gees-badge">'+e(nice(u.role))+'</span>';return '<tr data-user="'+e(u.id)+'"><td><strong>'+e(u.full_name||u.email||'User')+'</strong><span class="gees-table-subtext">'+e(u.email||u.id)+'</span></td><td>'+roleControl+'</td><td><select data-status-control>'+options(statusVals,u.status||'pending')+'</select></td><td><select data-team-control>'+options(teamVals,u.team_id||'')+'</select></td><td><div class="gees-inline-actions"><a class="gees-btn gees-btn-sm gees-btn-outline" href="'+detailsLink(u.id)+'">View</a><button class="gees-btn gees-btn-sm gees-btn-primary" data-save-user>Save</button></div></td></tr>'}).join(''):'<tr><td colspan="5"><div class="gees-record-empty">No users found.</div></td></tr>'}
async function save(root,tr){var id=tr.dataset.user;var payload={status:q('[data-status-control]',tr).value,team_id:q('[data-team-control]',tr).value||null,updated_at:new Date().toISOString()};var role=q('[data-role-control]',tr);if(role&&session.role==='super_admin')payload.role=role.value;set('[data-status="users"]','Saving user...','loading');var r=await client.from('profiles').update(payload).eq('id',id).select('id').maybeSingle();if(r.error)throw new Error(r.error.message);set('[data-status="users"]','User updated.','success');toast('User updated.');await refresh(root)}
async function start(){var root=q('[data-page="admin-users"]');if(!root)return;try{await boot();await refresh(root);root.addEventListener('click',async function(ev){var b=ev.target.closest('[data-save-user]');if(!b)return;ev.preventDefault();try{await save(root,ev.target.closest('[data-user]'))}catch(x){set('[data-status="users"]',x.message,'error');toast(x.message,'error')}})}catch(x){root.innerHTML='<div class="gees-live-only-note">'+e(x.message)+'</div>'}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
