(function(){
'use strict';
if(window.GEES_LEADS_V15)return;window.GEES_LEADS_V15=true;
var COOLDOWN_MS=60000;
var COOLDOWN_KEY='gees_public_lead_last_sent';
function ready(f){document.readyState==='loading'?document.addEventListener('DOMContentLoaded',f,{once:true}):f();}
function clean(v){return String(v||'').trim();}
function find(form,names){for(var i=0;i<names.length;i++){var el=form.querySelector('[name="'+names[i]+'"],#'+names[i]);if(el&&clean(el.value))return clean(el.value);}return '';}
function status(form,msg,type){if(form.id==='smartContactForm'){var toast=document.getElementById('contactToast');if(toast){toast.textContent=msg||'';toast.classList.add('show');window.setTimeout(function(){toast.classList.remove('show');},2800);return;}}var el=form.querySelector('[data-lead-status],[data-form-status],.form-status,.status-message');if(!el){el=document.createElement('div');el.setAttribute('data-lead-status','true');el.setAttribute('role','status');el.setAttribute('aria-live','polite');form.appendChild(el);}el.textContent=msg||'';el.dataset.type=type||'info';}
function button(form){return form.querySelector('button[type="submit"],input[type="submit"]');}
function busy(form,on,label){var b=button(form);if(!b)return;if(!b.dataset.geesLabel)b.dataset.geesLabel=b.tagName==='INPUT'?b.value:b.innerHTML;b.disabled=!!on;b.setAttribute('aria-busy',String(!!on));if(b.tagName==='INPUT')b.value=on?(label||'Sending...'):b.dataset.geesLabel;else b.innerHTML=on?'<span aria-hidden="true">…</span> '+(label||'Sending...'):b.dataset.geesLabel;}
function loadClient(){if(window.GEESWaitForSupabaseClient)return window.GEESWaitForSupabaseClient();return new Promise(function(resolve,reject){var s=document.querySelector('script[src*="/portal/shared/js/supabase-client.js"]');if(!s){s=document.createElement('script');s.src='/portal/shared/js/supabase-client.js?v=15.1.0';s.defer=true;document.head.appendChild(s);}var done=function(){window.GEESWaitForSupabaseClient?window.GEESWaitForSupabaseClient().then(resolve).catch(reject):reject(new Error('Supabase client unavailable.'));};s.addEventListener('load',done,{once:true});setTimeout(done,900);});}
function isLead(form){if(form.dataset.geesLeadForm==='true'||form.matches('[data-gees-lead-form]'))return true;var text=(form.textContent||'').toLowerCase();return /contact|consultation|message|phone|country|study/.test(text)&&form.querySelector('input,textarea,select');}
function data(form){var level=find(form,['study_level','studyLevel','preferred_level']),qualification=find(form,['academic_qualification','academicQualification']),timing=find(form,['apply_timing','applyTiming']),note=find(form,['message','studentMessage','notes','comment','query','description']);var details=[];if(level)details.push('Study level: '+level);if(qualification)details.push('Academic qualification: '+qualification);if(timing)details.push('Planned intake: '+timing);if(note)details.push(note);return{full_name:find(form,['full_name','name','fullname','student_name','studentName','contact_name']),email:find(form,['email','email_address','studentEmail']),phone:find(form,['phone','mobile','whatsapp','telephone','studentPhone']),preferred_country:find(form,['preferred_country','preferredCountry','country','destination','study_destination','studyDestination']),message:details.join('\n'),source:form.dataset.leadSource||(form.id==='smartContactForm'?'contact-us':(document.body.dataset.page||location.pathname)),status:'new'};}
function valid(p){if(p.full_name.length<2)return 'Please enter your full name.';if(!p.phone&&!p.email)return 'Please add your phone or email.';if(p.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(p.email))return 'Please enter a valid email address.';if(p.message.length>3000)return 'Your message is too long. Please keep it under 3,000 characters.';return '';}
function friendly(err){var raw=String((err&&err.message)||err||'').toLowerCase();if(/network|fetch|offline|timeout/.test(raw))return 'Connection issue. Please check your internet and try again.';if(/rate|too many/.test(raw))return 'Please wait a moment before sending another enquiry.';return 'We could not save your enquiry. Your WhatsApp request can still be sent.';}
function cooldownLeft(){try{return Math.max(0,COOLDOWN_MS-(Date.now()-Number(sessionStorage.getItem(COOLDOWN_KEY)||0)));}catch(e){return 0;}}
function setCooldown(){try{sessionStorage.setItem(COOLDOWN_KEY,String(Date.now()));}catch(e){}}
function ensureHoneypot(form){if(form.querySelector('[data-gees-honeypot]'))return;var wrap=document.createElement('div');wrap.hidden=true;wrap.setAttribute('aria-hidden','true');wrap.innerHTML='<label>Leave this field empty<input data-gees-honeypot name="company_website" type="text" tabindex="-1" autocomplete="off"></label>';form.appendChild(wrap);}
function bind(){Array.prototype.slice.call(document.querySelectorAll('form')).filter(isLead).forEach(function(form){if(form.dataset.geesLeadBound==='true')return;form.dataset.geesLeadBound='true';ensureHoneypot(form);form.addEventListener('submit',async function(e){if(form.dataset.skipSupabaseLead==='true'||!form.checkValidity())return;if(form.dataset.geesLeadBusy==='true'){e.preventDefault();e.stopImmediatePropagation();return;}var trap=form.querySelector('[data-gees-honeypot]');if(trap&&clean(trap.value)){e.preventDefault();e.stopImmediatePropagation();status(form,'Thank you. GEES received your enquiry.','success');return;}var left=cooldownLeft();if(left>0){e.preventDefault();e.stopImmediatePropagation();status(form,'Please wait '+Math.ceil(left/1000)+' seconds before sending another enquiry.','info');return;}var p=data(form),problem=valid(p);if(problem){e.preventDefault();e.stopImmediatePropagation();status(form,problem,'error');return;}form.dataset.geesLeadBusy='true';busy(form,true,'Saving…');try{var db=await loadClient();var r=await db.from('leads').insert(p).select('id').maybeSingle();if(r.error)throw new Error(r.error.message);setCooldown();if(form.id!=='smartContactForm')form.reset();try{document.dispatchEvent(new CustomEvent('gees:lead-submitted',{detail:{id:r.data&&r.data.id}}));}catch(ignore){}}catch(err){status(form,friendly(err),'error');}finally{form.dataset.geesLeadBusy='false';busy(form,false);}},true);});}
ready(bind);document.addEventListener('gees:page:ready',bind);window.GEESBindLeadForms=bind;
})();
