(function(){
'use strict';
if(window.GEES_LEADS_V14)return;window.GEES_LEADS_V14=true;
function ready(f){document.readyState==='loading'?document.addEventListener('DOMContentLoaded',f,{once:true}):f();}
function clean(v){return String(v||'').trim();}
function find(form,names){for(var i=0;i<names.length;i++){var el=form.querySelector('[name="'+names[i]+'"],#'+names[i]);if(el&&clean(el.value))return clean(el.value);}return '';}
function status(form,msg,type){var el=form.querySelector('[data-lead-status],[data-form-status],.form-status,.status-message');if(!el){el=document.createElement('div');el.setAttribute('data-lead-status','true');form.appendChild(el);}el.textContent=msg||'';el.dataset.type=type||'info';}
function loadClient(){if(window.GEESWaitForSupabaseClient)return window.GEESWaitForSupabaseClient();return new Promise(function(resolve,reject){var s=document.querySelector('script[src*="/portal/shared/js/supabase-client.js"]');if(!s){s=document.createElement('script');s.src='/portal/shared/js/supabase-client.js?v=14.5.0';s.defer=true;document.head.appendChild(s);}var done=function(){window.GEESWaitForSupabaseClient?window.GEESWaitForSupabaseClient().then(resolve).catch(reject):reject(new Error('Supabase client unavailable.'));};s.addEventListener('load',done,{once:true});setTimeout(done,900);});}
function isLead(form){if(form.dataset.geesLeadForm==='true'||form.matches('[data-gees-lead-form]'))return true;var text=(form.textContent||'').toLowerCase();return /contact|consultation|message|phone|country|study/.test(text)&&form.querySelector('input,textarea,select');}
function data(form){return{full_name:find(form,['full_name','name','fullname','student_name','contact_name'])||'GEES Website Visitor',email:find(form,['email','email_address']),phone:find(form,['phone','mobile','whatsapp','telephone']),preferred_country:find(form,['preferred_country','country','destination','study_destination']),message:find(form,['message','notes','comment','query','description']),source:form.dataset.leadSource||document.body.dataset.page||location.pathname,status:'new'};}
function bind(){Array.prototype.slice.call(document.querySelectorAll('form')).filter(isLead).forEach(function(form){if(form.dataset.geesLeadBound==='true')return;form.dataset.geesLeadBound='true';form.addEventListener('submit',async function(e){if(form.dataset.skipSupabaseLead==='true')return;e.preventDefault();var btn=form.querySelector('button[type="submit"],input[type="submit"]');if(btn)btn.disabled=true;status(form,'Sending your enquiry...','loading');try{var db=await loadClient();var p=data(form);if(!p.phone&&!p.email)throw new Error('Please add your phone or email.');var r=await db.from('leads').insert(p).select('id').maybeSingle();if(r.error)throw new Error(r.error.message);status(form,'Thank you. GEES received your enquiry.','success');form.reset();}catch(err){status(form,err.message||'Could not send enquiry.','error');}finally{if(btn)btn.disabled=false;}},true);});}
ready(bind);document.addEventListener('gees:page:ready',bind);window.GEESBindLeadForms=bind;
})();
